### PR TITLE
FIX_RILD_DUAL_SIM_SUPPORT_MSM8*25

### PR DESCRIPTION
**Pull request by weritos666**
FIX RILD DUAL SUPPORT MSM8*25

### CODE REVIEW

**Comment by weritos666** [comment]
rild

**Comment by neutrondev03** [comment]
Thank you very much. We have rild and libril from kitkat. For kitkat we are
not using qcomdsds for cm11.

**Comment by neutrondev03** [comment]
And i also used a ril class from l90 single sim and only ril is working
without data. I will update it when i get home.

**Comment by weritos666** [comment]
These changes and the source network starts RILD-legacy two SIM cards or one depending on the parameters.

**Comment by neutrondev03** [comment]
Ok i try.

**Pull request merged**
